name: Sampletheworld
favicon: null
layout_spectrum: 0.5298292252700776
typography_spectrum: 0.5891965937335044
title: Sample the World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6cfe0'
    - '#647798'
    - '#000000'
    - '#304765'
    - '#a89079'
  brandStrength: 0.5
  lightness: 0.5227797622792423
  saturation: 0.6092350124381483
  rhythmicContrast: 0.4668973688967526
purpose: []
