name: Sampletheworld
favicon: null
layout_spectrum: 0.5298292252700776
typography_spectrum: 0.5891965937335044
title: Sample the World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.37313919072039425
  lightness: 0.5227797622792423
  saturation: 0.6092350124381483
  rhythmicContrast: 0.4668973688967526
purpose: []
